/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

/**
 *
 * @author helder
 */

import UpperEatsClasses.Cliente;
import UpperEatsClasses.Encomenda;
import UpperEatsClasses.Refeicao;
import UpperEatsClasses.Restaurante;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import UpperEatsClasses.Encomenda.Estado;

public class EncomendarRefeicaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncomendarRefeicaoPanel
     */
    
    private static Cliente clienteAtual;
    
    ArrayList<Refeicao> refeicoesGuardar = new ArrayList<>();
    float total = 0;
    
    public EncomendarRefeicaoPanel() {
        initComponents();
    }
   
    
    void executar(Cliente cli) {
        clienteAtual = cli;
    }
    
    public void desativarPratosButton(){
        jComboBoxPratos.setEnabled(false);
        jComboBoxDose.setEnabled(false);
        jButton2.setEnabled(false);
    }
    
    public void ativarPratosButton(){
        jComboBoxPratos.setEnabled(true);
        jComboBoxDose.setEnabled(true);
        jButton2.setEnabled(true);
    }
    
    public void addicionarDadosTabela(Object[] dados){
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        tabela.addRow(dados);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        nomeRestaurante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        totalpagar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDose = new javax.swing.JComboBox();
        jComboBoxPratos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Continuar.png"))); // NOI18N
        jButton2.setText("Adicionar ao Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(240, 140, 226, 28);
        add(nomeRestaurante);
        nomeRestaurante.setBounds(220, 70, 140, 26);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("NOME RESTAURANTE:");
        add(jLabel2);
        jLabel2.setBounds(70, 80, 138, 16);

        jButton1.setText("Pesquisar Refeições");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(360, 70, 168, 29);

        totalpagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalpagar.setForeground(java.awt.Color.white);
        totalpagar.setText("Total:");
        add(totalpagar);
        totalpagar.setBounds(20, 300, 190, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Refeição", "Preço unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 170, 470, 120);

        jButton4.setText("Finalizar Encomenda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(240, 300, 173, 29);

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Escolha a Refeição");
        add(jLabel3);
        jLabel3.setBounds(70, 110, 116, 16);

        jComboBoxDose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dose", "Meia Dose" }));
        add(jComboBoxDose);
        jComboBoxDose.setBounds(360, 110, 168, 27);

        add(jComboBoxPratos);
        jComboBoxPratos.setBounds(210, 110, 140, 27);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menuComidas.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 343);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int num = jComboBoxPratos.getSelectedIndex();
        String opc = this.jComboBoxPratos.getItemAt(num).toString();
        int num1 = jComboBoxDose.getSelectedIndex();
        int count = 0;
        String opc1 = this.jComboBoxDose.getItemAt(num1).toString();
        ArrayList <Refeicao> refeicoes = new ArrayList<>();
        refeicoes = Repositorio.getInstance().pesquisarRefeicoes();

        Date data = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("HHmm");
        String dataHHMM = formatar.format(data);

        for(Refeicao r : refeicoes){
            System.out.println(r.getNome());
            if(r.getNome().equals(opc)){
                refeicoesGuardar.add(r);
                for(Refeicao re: refeicoesGuardar){
                    System.out.println(re);
                

                if(opc1.equals("Dose")){
                    int hora_momento = Integer.parseInt(dataHHMM);
                    System.out.println("hora momento " + hora_momento);
                    addicionarDadosTabela(new Object[]{r.getNome()+ " - Dose", r.getPrecoDose()});
                    total = (float) (total +r.getPrecoDose());
                    totalpagar.setText("Total: " + total + "€");
                }
            
                else if (opc1.equals("Meia Dose")){
                    int hora_momento = Integer.parseInt(dataHHMM);
                    System.out.println("hora momento " + hora_momento);
                    addicionarDadosTabela(new Object[]{r.getNome()+ " - Meia Dose", r.getPrecoMeiaDose()});
                    total = (float) (total +r.getPrecoMeiaDose());
                    totalpagar.setText("Total: " + total + "€");                 
                } else {
                    JOptionPane.showMessageDialog(null, "ERRO!");
                }
            }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jComboBoxPratos.removeAllItems();
        ativarPratosButton();
        ArrayList<Restaurante> res = Repositorio.getInstance().pesquisaPorNome(nomeRestaurante.getText());

        ArrayList <Refeicao> refeicoes = new ArrayList<>();
        refeicoes = Repositorio.getInstance().pesquisarRefeicoes();

        for(Refeicao r : refeicoes){
            if(r.getRes().getNomeRestaurante().equals(nomeRestaurante.getText())){
                jComboBoxPratos.addItem(r.getNome());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Date data = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("HHmm");
        String dataHHMM = formatar.format(data);
        int hora_momento = Integer.parseInt(dataHHMM);
        int num_encomenda = Repositorio.getInstance().getProximaEncomendaId();
        
        for(Refeicao re: refeicoesGuardar){
            System.out.println(re + " aa");
        }
        Encomenda encomenda = new Encomenda(num_encomenda,clienteAtual.getNumUtilizador(), data, hora_momento, false, this.refeicoesGuardar, 0, total, Estado.POR_ENTREGAR);
        for(Refeicao re: encomenda.getRef()){
            System.out.println(re + " bb");
        }
        try{
            Repositorio.desserializar();
            Repositorio.getInstance().novaEncomenda(encomenda);
            JOptionPane.showMessageDialog(null, "Encomenda Nº: " + num_encomenda + " registada com sucesso!!!");
            Repositorio.getInstance().proximaEncomenda();
            Repositorio.serializar();
        } catch (EncomendaDuplicadaException ex) {
            JOptionPane.showMessageDialog(null, "Erro! A Encomenda introduzida já existe!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBoxDose;
    private javax.swing.JComboBox jComboBoxPratos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeRestaurante;
    private javax.swing.JLabel totalpagar;
    // End of variables declaration//GEN-END:variables

}
