/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;
import UpperEatsClasses.Restaurante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author helder
 */
public class ProcurarRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form ProcurarRestaurante1
     */
    public ProcurarRestaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idRestaurante = new javax.swing.JRadioButton();
        tipoCozinha = new javax.swing.JRadioButton();
        nome = new javax.swing.JRadioButton();
        localidade = new javax.swing.JRadioButton();
        procura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        idRestaurante.setBackground(java.awt.Color.white);
        idRestaurante.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        idRestaurante.setForeground(java.awt.Color.white);
        idRestaurante.setText("ID Restaurante");

        tipoCozinha.setBackground(java.awt.Color.white);
        tipoCozinha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tipoCozinha.setForeground(java.awt.Color.white);
        tipoCozinha.setText("Tipo de Cozinha");
        tipoCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCozinhaActionPerformed(evt);
            }
        });

        nome.setBackground(java.awt.Color.white);
        nome.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nome.setForeground(java.awt.Color.white);
        nome.setText("Nome");

        localidade.setBackground(java.awt.Color.white);
        localidade.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        localidade.setForeground(java.awt.Color.white);
        localidade.setText("Localidade");
        localidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadeActionPerformed(evt);
            }
        });

        procura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procuraActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Localidade", "Nº Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Parâmetro de Procura");

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(400, 400, 400)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(tipoCozinha))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(480, 480, 480)
                            .addComponent(nome))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(localidade))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(480, 480, 480)
                            .addComponent(idRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(320, 320, 320)
                            .addComponent(procura, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(tipoCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(idRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(procura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCozinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCozinhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(idRestaurante.isSelected()){
            Restaurante res = Repositorio.getInstance().pesquisaPorCodigo(Integer.parseInt(procura.getText()));
            model.setRowCount(0);
            if(res == null){
                JOptionPane.showMessageDialog(null, "Não Existem Restaurantes");
            }
            else{
                model.addRow(new Object[]{res.getCodRestaurante(), res.getNomeRestaurante(),res.getLocalidade(),res.getnTelefone()});
            }
        }

        else if(localidade.isSelected()) {
            ArrayList<Restaurante> resultado = Repositorio.getInstance().pesquisaPorLocalidade(procura.getText());
            model.setRowCount(0);
            if(resultado.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existem Restaurantes");
            }
            else{
                for(Restaurante res: resultado){
                    model.addRow(new Object[]{res.getCodRestaurante(), res.getNomeRestaurante(),res.getLocalidade(), res.getnTelefone()});
                }
            }
        }

        else if(tipoCozinha.isSelected()) {
            ArrayList<Restaurante> res = Repositorio.getInstance().pesquisaPorTipodeCozinha(procura.getText());
            model.setRowCount(0);
            if(res.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existem Restaurantes");
            }
            else{
                for(Restaurante r: res){
                    model.addRow(new Object[]{r.getCodRestaurante(), r.getNomeRestaurante(),r.getLocalidade(), r.getnTelefone()});
                }
            }
        }
        else if(nome.isSelected()){
            ArrayList<Restaurante> resultado = Repositorio.getInstance().pesquisaPorNome(procura.getText());
            model.setRowCount(0);
            if(resultado.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existem Restaurantes");
            }
            else{
                for(Restaurante r: resultado){
                    model.addRow(new Object[]{r.getCodRestaurante(), r.getNomeRestaurante(),r.getLocalidade(),r.getnTelefone()});
                }
            }
        }
        else if(nome.isSelected()== false && tipoCozinha.isSelected() == false && localidade.isSelected() == false && idRestaurante.isSelected() == false )
        JOptionPane.showMessageDialog(null, "Selecione uma opção de pesquisa");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void procuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procuraActionPerformed

    private void localidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton idRestaurante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton localidade;
    private javax.swing.JRadioButton nome;
    private javax.swing.JTextField procura;
    private javax.swing.JRadioButton tipoCozinha;
    // End of variables declaration//GEN-END:variables
}
