/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.application.Platform;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import UpperEatsClasses.Cliente;
import UpperEatsClasses.DonoRestaurante;


/**
 *
 * @author Helder
 */
public class RegistarDonoRestaurante extends javax.swing.JFrame {

    private static Cliente esteCliente;
    
    /**
     * Creates new form RegistarCliente
     */
    public RegistarDonoRestaurante() {
        initComponents();
    }
    
    public void setEsteCliente(Cliente cliente){
        esteCliente = cliente;
    }
    
    public void close(){
 
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        ncc = new javax.swing.JLabel();
        nif = new javax.swing.JLabel();
        localidade = new javax.swing.JLabel();
        campoNCC = new javax.swing.JTextField();
        campoNIF = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoPassword = new javax.swing.JPasswordField();
        BotaoCancelar = new javax.swing.JButton();
        BotaoContinuar = new javax.swing.JButton();
        morada1 = new javax.swing.JLabel();
        campoMorada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoLocalidade = new javax.swing.JTextField();
        telefone = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        nome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nome.setText("Nome (Primeiro e Último)");
        getContentPane().add(nome);
        nome.setBounds(290, 120, 205, 21);

        ncc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ncc.setText("Numero de Cartão de Cidadão");
        getContentPane().add(ncc);
        ncc.setBounds(290, 180, 205, 21);

        nif.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nif.setText("NIF");
        getContentPane().add(nif);
        nif.setBounds(290, 240, 205, 21);

        localidade.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        localidade.setText("Localidade");
        getContentPane().add(localidade);
        localidade.setBounds(290, 420, 205, 21);

        campoNCC.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(campoNCC);
        campoNCC.setBounds(560, 170, 213, 30);

        campoNIF.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(campoNIF);
        campoNIF.setBounds(560, 230, 213, 30);

        campoTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(campoTelefone);
        campoTelefone.setBounds(560, 290, 213, 28);

        campoNome.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(campoNome);
        campoNome.setBounds(560, 110, 213, 30);

        campoPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        campoPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(campoPassword);
        campoPassword.setBounds(560, 470, 213, 28);

        BotaoCancelar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        BotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        BotaoCancelar.setText("Voltar");
        BotaoCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCancelar);
        BotaoCancelar.setBounds(330, 600, 140, 62);

        BotaoContinuar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        BotaoContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Registar.png"))); // NOI18N
        BotaoContinuar.setText("Registar");
        BotaoContinuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        BotaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoContinuar);
        BotaoContinuar.setBounds(599, 595, 149, 62);

        morada1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        morada1.setText("Morada");
        getContentPane().add(morada1);
        morada1.setBounds(290, 360, 205, 21);

        campoMorada.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(campoMorada);
        campoMorada.setBounds(560, 350, 213, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(295, 336, 36, 36);

        campoLocalidade.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        campoLocalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalidadeActionPerformed(evt);
            }
        });
        getContentPane().add(campoLocalidade);
        campoLocalidade.setBounds(560, 410, 213, 29);

        telefone.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        telefone.setText("Telefone");
        getContentPane().add(telefone);
        telefone.setBounds(290, 300, 205, 21);

        nome4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nome4.setText("Password");
        getContentPane().add(nome4);
        nome4.setBounds(290, 480, 205, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundRegistarCliente.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 810, 690);

        setSize(new java.awt.Dimension(821, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        MenuRegistar sc = new MenuRegistar();
        sc.setVisible(true);
        close();
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoContinuarActionPerformed

        try {
            Repositorio.desserializar();
            char[] pass = campoPassword.getPassword();
            String password = new String(pass);
            
            DonoRestaurante dono = new DonoRestaurante(campoNome.getText(), Integer.parseInt(campoNCC.getText()), Integer.parseInt(campoNIF.getText()), Integer.parseInt(campoTelefone.getText()),
            campoMorada.getText(), campoLocalidade.getText(),Repositorio.getInstance().getProximoUtilizadorId(),password);
            Repositorio.getInstance().novoDono(dono);
            JOptionPane.showMessageDialog(campoNome, " Dono Restaurante criado com sucesso, ID: " + Repositorio.getInstance().getProximoUtilizadorId()+"\nO ID É NECESSÁRIO PARA EFETUAR LOGIN!");
            Repositorio.getInstance().proximoUtilizador(); 
            Repositorio.serializar();            
            
            MenuDonoRestaurante fd = new MenuDonoRestaurante();
            fd.setCurrentDono(dono);
            fd.executar(dono);
            fd.setVisible(true);
            close();

        } catch (UtilizadorDuplicadoException ex) {
            JOptionPane.showMessageDialog(campoNome, "Erro! Utilizador já existente!");
        }
    }//GEN-LAST:event_BotaoContinuarActionPerformed

    private void campoLocalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarDonoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarDonoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarDonoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarDonoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarDonoRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoContinuar;
    private javax.swing.JTextField campoLocalidade;
    private javax.swing.JTextField campoMorada;
    private javax.swing.JTextField campoNCC;
    private javax.swing.JTextField campoNIF;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel localidade;
    private javax.swing.JLabel morada1;
    private javax.swing.JLabel ncc;
    private javax.swing.JLabel nif;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome4;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
