/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.Encomenda;
import UpperEatsClasses.Encomenda.Estado;
import UpperEatsClasses.Motard;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author helder
 */
public class ValidarEncomendas extends javax.swing.JPanel {

    /**
     * Creates new form ValidarEncomendas
     */
    public Motard m;
    
    public ValidarEncomendas() {
        initComponents();
    }
    
    public void setCurrentMotard(Motard motard){
        this.m = motard;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("Encomenda Entregue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID - Encomenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Repositorio.desserializar();
        ArrayList<Encomenda> pesquisa = Repositorio.getInstance().pesquisarEncomendas();
        
        for(Encomenda en : pesquisa){
            if(en.isPaga() == true){
                if(en.getNumReserva() == Integer.parseInt(id.getText())){
                    if(en.getnMotards()== m.getNumUtilizador()){
                        if(en.getEstado() == Estado.POR_ENTREGAR){
                    Repositorio.getInstance().alterarEncomenda(en.getNumReserva(), en.getNumCliente(), en.getData(), en.getHora(), en.isPaga(), en.getRef(),en.getnMotards(),en.getPrecoPagar(), Estado.ENTREGUE);
                    JOptionPane.showMessageDialog(null, "Encomenda Alterada para Entregue");
                } else {
                    JOptionPane.showMessageDialog(null, "Esta Encomenda já foi entregue!");
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Esta encomenda nao lhe pertence!");
                this.setVisible(false);
            }
        } else {
               JOptionPane.showMessageDialog(null, "Esta encomenda não existe!");
                this.setVisible(false); 
            }
    
    }//GEN-LAST:event_jButton1ActionPerformed
            else {
               JOptionPane.showMessageDialog(null, "Esta encomenda não está paga!");
                this.setVisible(false);  
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
