/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.DonoRestaurante;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author helder
 */
public class AlterarRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form AlteraRestaurante
     */
    private DonoRestaurante dono;
    
    public AlterarRestaurante() {
        initComponents();
    }
    
     public void setCurrentDono(DonoRestaurante dono){
        this.dono = dono;
    }
    
    public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        numeroRestaurante = new javax.swing.JTextField();
        jTxtMorada = new javax.swing.JTextField();
        alterarRestaurante = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tipoCozinha1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        localidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Morada");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 110, 140, 20);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tipo de Cozinha");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 190, 140, 20);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nome");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 30, 140, 20);
        getContentPane().add(jTxtNome);
        jTxtNome.setBounds(410, 20, 170, 30);
        getContentPane().add(numeroRestaurante);
        numeroRestaurante.setBounds(410, 60, 170, 30);
        getContentPane().add(jTxtMorada);
        jTxtMorada.setBounds(410, 100, 170, 30);

        alterarRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Continuar.png"))); // NOI18N
        alterarRestaurante.setText("Alterar Restaurante");
        alterarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(alterarRestaurante);
        alterarRestaurante.setBounds(360, 280, 160, 40);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Localidade");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 150, 140, 20);

        nTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(nTelefone);
        nTelefone.setBounds(410, 220, 170, 30);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Numero Restaurante");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 70, 140, 20);

        tipoCozinha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoCozinha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCozinha1ActionPerformed(evt);
            }
        });
        getContentPane().add(tipoCozinha1);
        tipoCozinha1.setBounds(410, 180, 170, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Número Telefone");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 230, 140, 20);

        localidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadeActionPerformed(evt);
            }
        });
        getContentPane().add(localidade);
        localidade.setBounds(410, 140, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundMenuInicial.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 350);

        setSize(new java.awt.Dimension(611, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarRestauranteActionPerformed

        try {
            Repositorio.desserializar();
            // TODO add your handling code here:
            Repositorio.getInstance().alteraRestaurante(Integer.parseInt(numeroRestaurante.getText()), dono, jTxtMorada.getText(), jTxtNome.getText(),tipoCozinha1.getText(), nTelefone.getText(), localidade.getText());
            JOptionPane.showMessageDialog(null, "Restaurante alterado com sucesso!");
            Repositorio.serializar();

        } catch (RestauranteInexistenteException ex) {
            JOptionPane.showMessageDialog(null, "Erro!! Recinto inexistente");
        } catch (AcessoRecusadoException ex) {
            JOptionPane.showMessageDialog(null, "Erro!! Acesso recusado");
        }
    }//GEN-LAST:event_alterarRestauranteActionPerformed

    private void nTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTelefoneActionPerformed

    private void tipoCozinha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCozinha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCozinha1ActionPerformed

    private void localidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtMorada;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField localidade;
    private javax.swing.JTextField nTelefone;
    private javax.swing.JTextField numeroRestaurante;
    private javax.swing.JTextField tipoCozinha1;
    // End of variables declaration//GEN-END:variables
}
