/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.Encomenda;
import UpperEatsClasses.Utilizador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author helder
 */
public class AtribuirMotardEncomenda extends javax.swing.JPanel {

    /**
     * Creates new form AtribuirMotardEncomenda
     */
    public AtribuirMotardEncomenda() {
        initComponents();
    }
    
    public void pesquisarEncomendasMotards(){
        
        Repositorio.desserializar();
        ArrayList<Encomenda> pesquisa = Repositorio.getInstance().pesquisarEncomendas();
        ArrayList<Utilizador> pesquisaMotard = Repositorio.getInstance().pesquisarMotards();
        
        for(Encomenda e : pesquisa){
            if(e.isPaga() == true){
                jComboBox1.addItem(e.getNumReserva());
            }
        }
        for(Utilizador u : pesquisaMotard){
            jComboBox2.addItem(u.getNumUtilizador());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Atribuir Motard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setText("Escolha a Encomenda: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 40, 150, -1));

        jLabel3.setText("Escolha o Motard: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Continuar.png"))); // NOI18N
        jButton1.setText("Atribuir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Repositorio.desserializar();
        ArrayList<Encomenda> pesquisa = Repositorio.getInstance().pesquisarEncomendas();
        ArrayList<Utilizador> pesquisaMotard = Repositorio.getInstance().pesquisarMotards();
        
        
        int num = jComboBox1.getSelectedIndex();
        int numeroEncomenda = Integer.parseInt(this.jComboBox1.getItemAt(num).toString());
        
        int num1 = jComboBox2.getSelectedIndex();
        int numeroMotard = Integer.parseInt(this.jComboBox2.getItemAt(num1).toString());
        String nomeMotard;
        
        for(Utilizador u: pesquisaMotard){
            if(u.getNumUtilizador() == numeroMotard){
                nomeMotard = u.getNome();
            }
        }
        for(Encomenda e : pesquisa){
            if(e.getNumReserva() == numeroEncomenda){
                if(e.getnMotards() == 0){
                Repositorio.getInstance().alterarEncomenda(e.getNumReserva(), e.getNumCliente(), e.getData(), e.getHora(), true, e.getRef(), numeroMotard, e.getPrecoPagar(),e.getEstado());
                Repositorio.serializar();
                for(Utilizador u:pesquisaMotard){
                    if(u.getNumUtilizador() == numeroMotard){
                    JOptionPane.showMessageDialog(null, "Encomenda: "+e.getNumReserva()+" Atribuida\nAo Motard - Nome: "+u.getNome());                

                    }
                }
                this.setVisible(false);      
            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
