/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.Refeicao;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author helder
 */
public class ConsultarRefeicoes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRefeicoes
     */
    public ConsultarRefeicoes() {
        initComponents();
    }
    
    public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procura = new javax.swing.JTextField();
        idRefeicao = new javax.swing.JRadioButton();
        nome = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        restaurante = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(procura);
        procura.setBounds(200, 50, 160, 30);

        idRefeicao.setForeground(java.awt.Color.white);
        idRefeicao.setText("Pesquisa por ID");
        idRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRefeicaoActionPerformed(evt);
            }
        });
        getContentPane().add(idRefeicao);
        idRefeicao.setBounds(20, 20, 130, 23);

        nome.setForeground(java.awt.Color.white);
        nome.setText("Pesquisa por Nome");
        getContentPane().add(nome);
        nome.setBounds(390, 20, 160, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID - Refeição", "Nome", "Preco Dose", "Preco Meia Dose", "Restaurante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 560, 320);

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 80, 104, 29);

        restaurante.setForeground(java.awt.Color.white);
        restaurante.setText("Pesquisar Por Restaurante");
        getContentPane().add(restaurante);
        restaurante.setBounds(180, 20, 200, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundLogin.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 440);

        setSize(new java.awt.Dimension(566, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        Repositorio.desserializar();
        
        ArrayList<Refeicao> resultado = Repositorio.getInstance().pesquisarRefeicoes();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        if(idRefeicao.isSelected()){
            if(resultado.isEmpty()){
               JOptionPane.showMessageDialog(null, "Não existem refeições!");
               close();
            }
            else{
                for(Refeicao r: resultado){
                    if(r.getCodRefeicao() == Integer.parseInt(procura.getText())){
                    model.addRow(new Object[]{r.getCodRefeicao(),r.getNome(), r.getPrecoDose(),r.getPrecoMeiaDose(),r.getRes().getNomeRestaurante()});
                }
            }
            }
        }
        
        else if(restaurante.isSelected()) {
            if(resultado.isEmpty()){
               JOptionPane.showMessageDialog(null, "Não existem refeições nesse Restaurante!");
               close();
            }
            else{
                for(Refeicao r: resultado){
                    if(r.getRes().getNomeRestaurante().equals(procura.getText())){
                    model.addRow(new Object[]{r.getCodRefeicao(),r.getNome(), r.getPrecoDose(),r.getPrecoMeiaDose(),r.getRes().getNomeRestaurante()});
                }
            }
        }
        }
        else if(nome.isSelected()){
            if(resultado.isEmpty()){
               JOptionPane.showMessageDialog(null, "Não existem refeições com esse nome!");
               close();
            }
            else{
                for(Refeicao r: resultado){
                    if(r.getNome().equals(procura.getText())){
                    model.addRow(new Object[]{r.getCodRefeicao(),r.getNome(), r.getPrecoDose(),r.getPrecoMeiaDose(),r.getRes().getNomeRestaurante()});
                }
            }
        }
        }
        else if(nome.isSelected()== false && nome.isSelected() == false && restaurante.isSelected() == false && idRefeicao.isSelected() == false )
        JOptionPane.showMessageDialog(null, "Selecione uma opção de pesquisa!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRefeicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRefeicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarRefeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarRefeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarRefeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarRefeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarRefeicoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton idRefeicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton nome;
    private javax.swing.JTextField procura;
    private javax.swing.JRadioButton restaurante;
    // End of variables declaration//GEN-END:variables
}
