/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.DonoRestaurante;
import UpperEatsClasses.Refeicao;
import UpperEatsClasses.Restaurante;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author helder
 */
public class CriarRefeicao extends javax.swing.JFrame {

    /**
     * Creates new form CriarRefeicao
     */
    DonoRestaurante dono;

    public DonoRestaurante getDono() {
        return dono;
    }

    public void setDono(DonoRestaurante dono) {
        this.dono = dono;
    }
    
     public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    
    
    public CriarRefeicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nomePrato = new javax.swing.JTextField();
        precoDose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        precoMeiaDose = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        restauranteID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOME PRATO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 50, 120, 18);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRECO DOSE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 120, 18);

        jButton1.setText("Criar Refeicao");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 220, 152, 29);
        getContentPane().add(nomePrato);
        nomePrato.setBounds(270, 50, 107, 26);
        getContentPane().add(precoDose);
        precoDose.setBounds(270, 100, 107, 26);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESTAURANTE - ID");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 190, 130, 18);
        getContentPane().add(precoMeiaDose);
        precoMeiaDose.setBounds(270, 140, 107, 26);

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRECO MEIA DOSE");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 140, 120, 18);

        restauranteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restauranteIDActionPerformed(evt);
            }
        });
        getContentPane().add(restauranteID);
        restauranteID.setBounds(270, 180, 110, 26);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(400, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     Restaurante res = Repositorio.getInstance().pesquisaPorCodigo(Integer.parseInt(restauranteID.getText()));
        
     if(res.getDono().getNumUtilizador() == dono.getNumUtilizador()){  
        Refeicao r = new Refeicao(Repositorio.getInstance().getProximaRefeicaoId(), nomePrato.getText(),Float.parseFloat(precoDose.getText()),Float.parseFloat(precoMeiaDose.getText()), res);

        try{
            Repositorio.desserializar();
            Repositorio.getInstance().novaRefeicao(r);
            close();
            JOptionPane.showMessageDialog(null, "Refeição: "+nomePrato.getText()+" criado com sucesso - ID: "+Repositorio.getInstance().getProximaRefeicaoId());
            close();
            Repositorio.getInstance().ProximaRefeicaoId();
            Repositorio.serializar();

        } catch (RefeicaoDuplicadaException ex) {
            JOptionPane.showMessageDialog(null, "Erro!! Refeicao já existente");
        }    
        MenuDonoRestaurante mdr = new MenuDonoRestaurante();
        mdr.setCurrentDono(dono);
        close();
        mdr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
     else {
         JOptionPane.showMessageDialog(null, "Erro! Este restaurante não lhe pertence!");
         close();
     }
    }
    
    
    
    private void restauranteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restauranteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restauranteIDActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarRefeicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarRefeicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomePrato;
    private javax.swing.JTextField precoDose;
    private javax.swing.JTextField precoMeiaDose;
    private javax.swing.JTextField restauranteID;
    // End of variables declaration//GEN-END:variables
}
