/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import UpperEatsClasses.Admin;
import UpperEatsClasses.Cliente;
import UpperEatsClasses.DonoRestaurante;
import UpperEatsClasses.Motard;
import UpperEatsClasses.Utilizador;

/**
 *
 * @author Utilizador
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Repositorio.desserializar();
    }

    public void close(){
 
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        continuar = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        campoUsername.setBackground(java.awt.Color.darkGray);
        campoUsername.setForeground(java.awt.Color.white);
        getContentPane().add(campoUsername);
        campoUsername.setBounds(310, 170, 180, 50);

        jLabel2.setBackground(java.awt.Color.darkGray);
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 240, 160, 40);

        jLabel1.setBackground(java.awt.Color.darkGray);
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID CLIENTE");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 180, 160, 40);

        campoPassword.setBackground(java.awt.Color.darkGray);
        campoPassword.setForeground(java.awt.Color.white);
        getContentPane().add(campoPassword);
        campoPassword.setBounds(310, 240, 180, 50);

        continuar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.png"))); // NOI18N
        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar);
        continuar.setBounds(440, 320, 170, 50);

        jToggleButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(30, 320, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 390);

        setSize(new java.awt.Dimension(644, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
  // TODO add your handling code here:
        int id = Integer.parseInt(campoUsername.getText());
        char[] pass = campoPassword.getPassword();
        String password = new String(pass);
        
        //Instanciar um utilizador abrindo o repositorio
        Utilizador util = Repositorio.getInstance().login(id, password);
        
        //Se esse utilizador for um DonoRestaurante abrir o seu respetivo menu
        if(util instanceof DonoRestaurante) {
            MenuDonoRestaurante f = new MenuDonoRestaurante(); 
            this.setVisible(false);
            f.setVisible(true);
            DonoRestaurante d = (DonoRestaurante)util;
            f.executar(d);
            f.setCurrentDono(d);
        }
        //Se for Cliente:
        else if(util instanceof Cliente) {
            MenuCliente fc = new MenuCliente();
            this.setVisible(false);
            fc.setVisible(true);
            Cliente c = (Cliente)util;
            fc.executar(c);
            fc.setCurrentCliente(c);
        } //Caso seja Admin;
        else if(util instanceof Admin){
            MenuAdmin fa = new MenuAdmin();
            this.setVisible(false);
            fa.setVisible(true);
            Admin a = (Admin)util;
            fa.setCurrentAdmin(a);
            fa.executar(); 
        } else if ( id == 5 && "helder".equals(password)){
            MenuAdmin fa = new MenuAdmin();
            fa.setCurrentAdmin(null);
            fa.executar();
            this.setVisible(false);
            fa.setVisible(true);
        } else if(util instanceof Motard){
            MenuMotard mm = new MenuMotard();
            this.setVisible(false);
            mm.setVisible(true);
            Motard motard = (Motard)util;
            mm.setCurrentMotard(motard);
            mm.executar();
        }  
        else //Caso contrario lancamento de uma exceção
            JOptionPane.showMessageDialog(null, "Utilizador inexistente");


        
    }//GEN-LAST:event_continuarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MenuInicial menu = new MenuInicial();
        menu.setVisible(true);
        close();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JToggleButton continuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
