/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Helder
 */
public class MenuRegistar extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistar
     */
    public MenuRegistar() {
        initComponents();
    }
    
public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistarDono = new javax.swing.JButton();
        RegistarCliente3 = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        RegistarDono.setBackground(java.awt.Color.darkGray);
        RegistarDono.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        RegistarDono.setForeground(java.awt.Color.white);
        RegistarDono.setText("Registar Dono Restaurante");
        RegistarDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarDonoActionPerformed(evt);
            }
        });
        getContentPane().add(RegistarDono);
        RegistarDono.setBounds(280, 180, 190, 61);

        RegistarCliente3.setBackground(java.awt.Color.darkGray);
        RegistarCliente3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        RegistarCliente3.setForeground(java.awt.Color.white);
        RegistarCliente3.setText("Registar Cliente");
        RegistarCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarCliente3ActionPerformed(evt);
            }
        });
        getContentPane().add(RegistarCliente3);
        RegistarCliente3.setBounds(280, 70, 190, 62);

        Voltar.setBackground(java.awt.Color.darkGray);
        Voltar.setForeground(java.awt.Color.white);
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 0, 97, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundMenuInicial.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 320);

        setSize(new java.awt.Dimension(554, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarDonoActionPerformed
        // TODO add your handling code here:
       RegistarDonoRestaurante menu = new RegistarDonoRestaurante();
       menu.setVisible(true);
       close();

    }//GEN-LAST:event_RegistarDonoActionPerformed

    private void RegistarCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarCliente3ActionPerformed
        // TODO add your handling code here:
        RegistarCliente cliente = new RegistarCliente();
        cliente.setVisible(true);
        close();
    }//GEN-LAST:event_RegistarCliente3ActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        close();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuRegistar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistarCliente3;
    private javax.swing.JButton RegistarDono;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
