/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIandExceptions;

import UpperEatsClasses.Cliente;
import UpperEatsClasses.Encomenda;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author helder
 */
public class PagarEncomenda extends javax.swing.JPanel {

    /**
     * Creates new form PagarEncomenda
     */
    
    float totalPagar;
    
    private static Cliente clienteAtivo;
    int count = 0;
    int numero;

    public void setCliente(Cliente c){
        clienteAtivo = c;
    }
    
    public PagarEncomenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtxtvalor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        idEncomenda = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("Executar Pagamento");
        add(jLabel1);
        jLabel1.setBounds(147, 6, 127, 16);

        jLabel2.setText("ID - Encomenda Deseja Pagar?");
        add(jLabel2);
        jLabel2.setBounds(6, 45, 191, 16);

        total.setText("Total a Pagar : ");
        add(total);
        total.setBounds(100, 80, 230, 20);

        jLabel4.setText("Insira o Valor a Pagar :");
        add(jLabel4);
        jLabel4.setBounds(50, 130, 140, 16);

        jButton1.setText("Escolher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(306, 40, 97, 29);
        add(jtxtvalor);
        jtxtvalor.setBounds(200, 120, 186, 26);

        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(150, 170, 102, 31);
        add(idEncomenda);
        idEncomenda.setBounds(200, 40, 100, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtvalor.setEnabled(true);
        jButton2.setEnabled(true);        
        numero = Integer.parseInt(idEncomenda.getText());
        
        ArrayList<Encomenda> pesquisa = Repositorio.getInstance().pesquisarEncomendas();

        for(Encomenda en : pesquisa){
            if(numero == en.getNumReserva()){
                total.setText("Total a Pagar : " + en.getPrecoPagar()+ "€");
                totalPagar = en.getPrecoPagar();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        float valorRecebido = Float.parseFloat(jtxtvalor.getText());
        
        ArrayList<Encomenda> pesquisa = Repositorio.getInstance().pesquisarEncomendas();

        if(valorRecebido == totalPagar){
            JOptionPane.showMessageDialog(null, "Pagamento efetuado com sucesso! Obrigado");

            for(Encomenda en : pesquisa){
                if(numero == en.getNumReserva()){
                    Repositorio.desserializar();
                    Repositorio.getInstance().alterarEncomenda(en.getNumReserva(), en.getNumCliente(), en.getData(), en.getHora(), true, en.getRef(), en.getnMotards(), 0,en.getEstado());
                    Repositorio.serializar();
                }
            }
        }
        if(valorRecebido > totalPagar){
            float troco = valorRecebido - totalPagar;
            JOptionPane.showMessageDialog(null, "Pagamento executado com sucesso! TROCO: " + troco + "€");
            for(Encomenda en : pesquisa){
                if(numero == en.getNumReserva()){
                    Repositorio.getInstance().alterarEncomenda(en.getNumReserva(), en.getNumCliente(), en.getData(), en.getHora(), true, en.getRef(), en.getnMotards(), 0,en.getEstado());
                }
            }
        }
        if(valorRecebido < totalPagar){
            float faltaPagar = totalPagar- valorRecebido;
            JOptionPane.showMessageDialog(null, "Falta pagar " + faltaPagar + "€ Por favor Insira a quantia correta!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idEncomenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtxtvalor;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
